### ISSUE TITLE
3D Simulation

### ISSUE THREAD

**Issue by xuhenry** [ppizarror/FNELEM-GPU#2]
Hello,
   Will the code be developed for the simulation of solid in 3D?
Thanks a lot!
Best regards,
Henry

**Comment by ppizarror** [comment]
Hi, this is a small project of mine to practice some techniques in finite elements (As I'm student of civil structural engineering + computer science). By this time I do not intend to write any code.

3D simulation is very similar, only a new stifness and interpolation matrix are needed. Maybe in the future I'll work on this, but now my mind is focused in machine learning.

Greetings from Chile!
Pablo
